variables:
  GIT_SUBMODULE_STRATEGY: normal

default:
  image: fjmolinas/riotpepper

stages:
  - static-checks
  - build
  - test

build:
  stage: build
  script:
    - make -j

test:
  stage: test
  script:
    - make test -j

cppcheck:
  stage: static-checks
  allow_failure: true
  script:
    - cppcheck --enable=style --quiet ./modules/ ./tests/
