variables:
  GIT_SUBMODULE_STRATEGY: normal

default:
  image: fjmolinas/riotpepper

stages:
  - static-checks
  - build
  - test

build:
  tags:
    - ci.inria.fr
    - large
  stage: build
  script:
    - make -j
  only:
    - master
    - merge_requests

test:
  tags:
    - ci.inria.fr
    - large
  stage: test
  script:
    - make test -j
  only:
    - master
    - merge_requests

cppcheck:
  tags:
    - ci.inria.fr
    - small
  stage: static-checks
  allow_failure: true
  script:
    - cppcheck --enable=style --quiet ./modules/ ./tests/
  only:
    - master
    - merge_requests

pages:
  image: alpine
  tags:
    - ci.inria.fr
    - small
  script:
  - apk update && apk add doxygen graphviz ttf-freefont
  - doxygen docs/Doxyfile
  - mv docs/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
  - develop
