#!/usr/bin/env bash

# parse arguments
while getopts "b:i:p" name; do
  case $name in
    b)  b="$OPTARG";;
    i)  i="$OPTARG";;
    p)  p="$OPTARG";;
    ?)  printf "Usage: %s [-b baudrate] [-i interval] [-p port]\n" "$0"
        exit 2;;
  esac
done

# Default Advertisement Interval
if [ -z "$i" ]; then
    readonly INTERVAL=60
else
    readonly INTERVAL=$i
fi

# Default Port
if [ -z "$p" ]; then
    readonly PORT=/dev/riot/tty-bletimeadv
else
    readonly PORT=$p
fi

# Default Baudrate
if [ -z "$p" ]; then
    readonly BAUDRATE=115200
else
    readonly BAUDRATE=$b
fi

set_time() {
    echo "Set time to..."
    local cur_datetime
    cur_datetime=$(date +'%Y %m %d %H %M %S')
    echo "time ${cur_datetime}" | socat - open:"${PORT}",b"${BAUDRATE}",echo=0,raw
}

start_adv_time() {
    echo "Start Adv..."
    echo "start ${INTERVAL}" | socat - open:"${PORT}",b"${BAUDRATE}",echo=0,raw
}

cleanup() {
    echo "Cleaning up..."
    trap "" INT QUIT TERM EXIT
}

main() {
    set_time
    sleep 1
    start_adv_time
}

trap "cleanup" INT QUIT TERM EXIT
main "$@"
