USEMODULE += ebid
USEMODULE += uwb_ed
USEMODULE += crypto_manager

USEMODULE += fmt
USEMODULE += memarray

OUTPUT_FORMAT ?= json
USEMODULE += test_utils_result_output_${OUTPUT_FORMAT}

USEPKG += nanocbor
