USEMODULE_INCLUDES_desire_advertiser := $(LAST_MAKEFILEDIR)/include
USEMODULE_INCLUDES += $(USEMODULE_INCLUDES_desire_advertiser)

USEMODULE_INCLUDES += $(USEMODULE_INCLUDES_desire_advertiser)/../../include

PSEUDOMODULES += desire_advertiser_threaded
PSEUDOMODULES += desire_advertiser_shell

CFLAGS += -DMYNEWT_VAL_BLE_LL_SCAN_AUX_SEGMENT_CNT=1
