MODULE_DESIRE_ADVERTISER_DIR := $(LAST_MAKEFILEDIR)

# configure and use Nimble pkg with the autoadv without name and manual start from our app
USEPKG += nimble
USEMODULE += nimble_svc_gap
USEMODULE += nimble_autoadv
CFLAGS += -DNIMBLE_AUTOADV_START_MANUALLY=1
CFLAGS += -DNIMBLE_AUTOADV_DEVICE_NAME=NULL
CFLAGS += -DNIMBLE_AUTOADV_FLAG_FIELD=0

# EBID module
USEMODULE += ebid
CFLAGS += -DEBID_FIXED_KEYS=0
EXTERNAL_MODULE_DIRS += $(MODULE_DESIRE_ADVERTISER_DIR)/../../sys/ebid

# event module
USEMODULE += event_timeout
USEMODULE += event_thread
