USEMODULE_INCLUDES_desire_advertiser := $(LAST_MAKEFILEDIR)/include
USEMODULE_INCLUDES += $(USEMODULE_INCLUDES_desire_advertiser)

USEMODULE_INCLUDES += $(USEMODULE_INCLUDES_desire_advertiser)/../../include

PSEUDOMODULES += desire_advertiser_threaded
