USEPKG += nimble
USEMODULE += nimble_svc_gap
USEMODULE += nimble_adv_ext
USEMODULE += bluetil_ad

USEMODULE += ebid

USEMODULE += event
USEMODULE += event_timeout_ztimer
ifneq (,$(filter desire_advertiser_threaded,$(USEMODULE)))
  USEMODULE += event_thread
endif

ifneq (,$(filter desire_advertiser_shell,$(USEMODULE)))
  USEMODULE += shell
  USEMODULE += shell_commands
  USEMODULE += pepper
  USEMODULE += random
endif

USEMODULE += ztimer_msec
