MODULE_DESIRE_SCANNER_DIR := $(LAST_MAKEFILEDIR)

# configure and use Nimble pkg with the autoadv without name and manual start from our app
USEPKG += nimble
USEMODULE += nimble_scanner
USEMODULE += bluetil_ad

# EBID module
USEMODULE += ebid
CFLAGS += -DEBID_FIXED_KEYS=0
EXTERNAL_MODULE_DIRS += $(MODULE_DESIRE_SCANNER_DIR)/../../sys/ebid

USEMODULE += ztimer_msec
USEMODULE += ztimer_usec
