# configure and use Nimble pkg with the autoadv without name and manual start from our app
USEPKG += nimble
USEMODULE += nimble_scanner
USEMODULE += bluetil_ad
USEMODULE += ebid
USEMODULE += ztimer_msec

ifneq (,$(filter desire_scanner_netif,$(USEMODULE)))
  USEMODULE += nimble_netif
  USEMODULE += gnrc_netdev_default
  USEMODULE += gnrc_netif_single
  USEMODULE += auto_init_gnrc_netif
  USEMODULE += gnrc_ipv6_router_default
  USEMODULE += gnrc_icmpv6_echo
endif
