ifneq (,$(filter pepper_controller,$(USEMODULE)))
  USEMODULE += epoch
  USEMODULE += ebid
  USEMODULE += crypto_manager
  USEMODULE += twr
  USEMODULE += ed
  USEMODULE += fmt
  USEMODULE += event
  USEMODULE += event_thread
  USEMODULE += event_thread_highest
  USEMODULE += event_callback
  USEMODULE += event_periodic
  USEMODULE += event_timeout_ztimer
  USEMODULE += desire_scanner
  USEMODULE += desire_advertiser
  USEMODULE += ztimer_epoch
  USEMODULE += ztimer_msec
  USEMODULE += ztimer_sec
endif

ifneq (,$(filter pepper_gatt,$(USEMODULE)))
  USEMODULE += nimble_autoadv
  USEMODULE += nimble_svc_gap
  USEMODULE += nimble_svc_gatt
  USEMODULE += pepper_util
endif

ifneq (,$(filter pepper_stdio_nimble,$(USEMODULE)))
  USEMODULE += pepper_util
  USEMODULE += stdio_nimble
endif

ifneq (,$(filter pepper_util,$(USEMODULE)))
  USEMODULE += luid
  USEMODULE += fmt
endif

ifneq (,$(filter pepper_current_time,$(USEMODULE)))
  USEMODULE += current_time
  # TODO: move this to its own service
  USEMODULE += desire_scanner
  USEMODULE += desire_scanner_time_update
endif
