ifneq (,$(filter pepper_controller,$(USEMODULE)))
  USEMODULE += epoch
  USEMODULE += ebid
  USEMODULE += crypto_manager
  USEMODULE += ed
  USEMODULE += fmt
  USEMODULE += event
  USEMODULE += event_thread
  USEMODULE += event_thread_highest
  USEMODULE += event_callback
  USEMODULE += event_periodic
  USEMODULE += event_timeout_ztimer
  USEMODULE += desire_scanner
  USEMODULE += desire_advertiser
  USEMODULE += ztimer_epoch
  USEMODULE += ztimer_msec
  USEMODULE += ztimer_sec
  ifneq (,$(filter ed_uwb,$(USEMODULE)))
    USEMODULE += twr
  endif
endif

ifneq (,$(filter pepper_gatt,$(USEMODULE)))
  USEMODULE += nimble_autoadv
  USEMODULE += nimble_svc_gap
  USEMODULE += nimble_svc_gatt
  USEMODULE += pepper_util
endif

ifneq (,$(filter pepper_stdio_nimble,$(USEMODULE)))
  USEMODULE += pepper_util
  USEMODULE += stdio_nimble
endif

ifneq (,$(filter pepper_util,$(USEMODULE)))
  USEMODULE += luid
  USEMODULE += fmt
endif

ifneq (,$(filter pepper_current_time,$(USEMODULE)))
  USEMODULE += current_time
  USEMODULE += current_time_ble_scanner
endif
