USEMODULE += epoch
USEMODULE += pepper
USEMODULE += pepper_util

ifneq (,$(filter pepper_srv_shell,$(USEMODULE)))
  USEMODULE += shell
  USEMODULE += shell_commands
  USEMODULE += pepper
endif

ifneq (,$(filter pepper_srv_storage,$(USEMODULE)))
  USEMODULE += storage
  USEMODULE += mtd_sdcard
  USEMODULE += ztimer_msec
endif

ifneq (,$(filter pepper_srv_utils,$(USEMODULE)))
  USEPKG += nanocbor
endif

ifneq (,$(filter pepper_srv_coap,$(USEMODULE)))
  USEMODULE += pepper_srv_utils
endif

ifneq (,$(filter pepper_srv_coaps,$(USEMODULE)))

endif
