USEMODULE += epoch

ifneq (,$(filter pepper_srv_shell,$(USEMODULE)))
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += pepper
USEMODULE += pepper_util
endif

ifneq (,$(filter pepper_srv_storage,$(USEMODULE)))
endif

ifneq (,$(filter pepper_srv_coap,$(USEMODULE)))
endif

ifneq (,$(filter pepper_srv_coaps,$(USEMODULE)))
endif