USEMODULE_INCLUDES_pepper_srv := $(LAST_MAKEFILEDIR)/include
USEMODULE_INCLUDES += $(USEMODULE_INCLUDES_pepper_srv)

PSEUDOMODULES += pepper_srv_shell
PSEUDOMODULES += pepper_srv_coap
PSEUDOMODULES += pepper_srv_storage
PSEUDOMODULES += pepper_srv_utils

