# use JLink Segger RTT by default
RIOT_TERMINAL ?= jlink

PROGRAMMER ?= debuggoid
PROGRAMMERS_SUPPORTED += debuggoid

# include common configuration for nrf52 based boards
include $(RIOTBOARD)/common/nrf52/Makefile.include
