ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += lis2dh12
endif

# Use Segger's RTT unless another stdio_% is already used
ifeq (,$(filter stdio_% slipdev_stdio,$(USEMODULE)))
  USEMODULE += stdio_rtt
endif

# include common nrf52 dependencies
include $(RIOTBOARD)/common/nrf52/Makefile.dep
