USEMODULE += ebid
USEMODULE += memarray

ifneq (,$(filter uwb_ed_bpf,$(USEMODULE)))
  USEMODULE += bpf
  USEMODULE += suit
  USEMODULE += suit_storage_ram
  USEMODULE += suit_transport_coap
  USEMODULE += gcoap
endif
